### ISSUE TITLE
Accept epoch time `tspan`

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/SimulationService.jl#5]
This should allow the returned `csv` to have epoch time (human time) instead of ethereal time steps (e.g. `0 to 100`).

**Comment by anandijain** [comment]
The simplest solution is that you guys just give me non-string epoch times as a list, ie `{"tspan":[1.677598576457e9,1.677598676457e9]}`, since this just works without modification. Then in the simulation config, you could specify the timestep size with `"saveat": 86400` for saving each day. 

Let me know if that's sufficient

**Comment by brandomr** [comment]
I think that would work well. @mwdchang any concerns?

**Comment by anandijain** [comment]
we agreed to pass in tspan: [number, number] as epoch times
